name: Ai Code Quality Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  

jobs:
    # -------------------
    # Step 1: CodeGuru Reviewer
    # -------------------
    codeguru-review:
        runs-on: ubuntu-22.04

        steps:
          - name: Checkout code
            uses: actions/checkout@v2
            with:
                fetch-depth: 0
          
          - name: Clean up unneeded files
            run: |
              rm -rf .venv __pycache__ .pytest_cache node_modules || true
              sudo apt-get clean

          - name: Set up AWS credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1

          - name: Run CodeGuru Reviewer
            uses: aws-actions/codeguru-reviewer@v1.1
            with:
                build_path: data
                s3_bucket: ${{ secrets.S3_BUCKET }}
        
          - name: Upload SARIF as artifact
            uses: actions/upload-artifact@v4
            with:
                name: codeguru-sarif
                path: codeguru-results.sarif.json
                retention-days: 1

          - name: Upload review result
            if: ${{ github.event_name != 'push' }}
            uses: github/codeql-action/upload-sarif@v1
            with:
                sarif_file: codeguru-results.sarif.json

    # -------------------
    # Step 2: Run CodeGuru Security
    # -------------------
    codeguru-security:
        runs-on: ubuntu-latest
        needs: codeguru-review

        steps:
            # Step 1: Checkout the repo
            - name: Checkout Code       
              uses: actions/checkout@v3
            
            # Step 2: Set up Python
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'
            
            # Step 3: Install dependencies
            - name: Install Dependencies
              run: |
                pip install poetry
                poetry install
            
            # Step 4: Run Code Guru Security
            - name: Run CodeGuru Security Scanner
              run: |
                poetry run python automation/codeguru_security.py
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: us-east-1

    # -------------------
    # Step 3: Run NLP
    # -------------------   
    nlp-analysis:
        runs-on: ubuntu-latest
        needs: codeguru-security

        steps:
          - name: Checkout Code
            uses: actions/checkout@v3

          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.12'

          - name: Install Dependencies
            run: |
              pip install poetry
              poetry install

          - name: Run NLP Comment Quality Scanner
            run: |
              poetry run python automation/nlp_comment_check.py
            env:
              OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
    # -------------------
    # Step 4: Post GitHub Issue with Combined Results
    # -------------------
    post-github-issue:
        name: Post GitHub Issue
        needs: nlp-analysis
        runs-on: ubuntu-latest

        steps:
          - name: Checkout Code
            uses: actions/checkout@v3

          - name: Download SARIF Artifact
            uses: actions/download-artifact@v4
            with:
                name: codeguru-sarif
                path: sarif-artifacts

          - name: Set up Python
            uses: actions/setup-python@v4
            with:
                python-version: '3.12'

          - name: Install Dependencies
            run: |
                pip install poetry
                poetry install

          - name: Run Python Script to Format & Post GitHub Issue
            run: |
                poetry run python automation/github_issues.py
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    